#!/bin/bash

exec ./slack-wrap \
	--ignore '^\s*quit$' \
	--ignore '^\s*q\s*$' \
	--ignore '^[<\\]' \
	--filter 's/^>\s*>\s*$//msg' \
	--channel "C0454BJ1A" \
	--user frotz \
	-- \
	./frotz/dfrotz ./frotz/trinity.z3

exit 0
